# Generated by Django 2.1 on 2018-08-22 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoProspeccao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_fluxo', models.CharField(max_length=60, verbose_name='Descrição do Fluxo')),
                ('qtd_passos', models.IntegerField(verbose_name='Quantidade Passos')),
                ('qtd_contatos1', models.IntegerField(default=0, verbose_name='Quantidade Contatos')),
                ('qtd_contatos2', models.IntegerField(default=0, verbose_name='Quantidade Contatos')),
                ('qtd_contatos3', models.IntegerField(default=0, verbose_name='Quantidade Contatos')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Master')),
            ],
            options={
                'verbose_name': 'Fluxo Prospecção',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('razao', models.CharField(max_length=60, verbose_name='Razão/Nome')),
                ('fantasia', models.CharField(blank=True, max_length=40, null=True, verbose_name='Fantasia')),
                ('cep', models.CharField(blank=True, max_length=12, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=40, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de cadastro')),
                ('situacao', models.BooleanField(default=True, verbose_name='Ativo')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Master')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='StatusProspeccao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_desc', models.CharField(max_length=40, verbose_name='Descrição')),
                ('intervalo', models.IntegerField(verbose_name='Intervalo de retorno (dias)')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Master')),
            ],
            options={
                'verbose_name': 'Status Prospecção',
            },
        ),
        migrations.AddField(
            model_name='fluxoprospeccao',
            name='passo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passo1', to='cadastros.StatusProspeccao', verbose_name='Passo1'),
        ),
        migrations.AddField(
            model_name='fluxoprospeccao',
            name='passo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passo2', to='cadastros.StatusProspeccao', verbose_name='Passo2'),
        ),
        migrations.AddField(
            model_name='fluxoprospeccao',
            name='passo3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passo3', to='cadastros.StatusProspeccao', verbose_name='Passo3'),
        ),
        migrations.AddField(
            model_name='fluxoprospeccao',
            name='passo_falha1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passo_falha1', to='cadastros.StatusProspeccao', verbose_name='Próximo Passo - Falha'),
        ),
        migrations.AddField(
            model_name='fluxoprospeccao',
            name='passo_falha2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passo_falha2', to='cadastros.StatusProspeccao', verbose_name='Próximo Passo - Falha'),
        ),
        migrations.AddField(
            model_name='fluxoprospeccao',
            name='passo_falha3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passo_falha3', to='cadastros.StatusProspeccao', verbose_name='Próximo Passo - Falha'),
        ),
        migrations.AlterUniqueTogether(
            name='statusprospeccao',
            unique_together={('master_user', 'status_desc')},
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('master_user', 'cnpj_cpf')},
        ),
        migrations.AlterUniqueTogether(
            name='fluxoprospeccao',
            unique_together={('master_user', 'desc_fluxo')},
        ),
    ]
