# Generated by Django 2.1 on 2018-08-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180809_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qtd_users',
        ),
    ]
